version: '3.8'
services:

  postgres:
    image: postgres:13.3
    container_name: postgres_container
    environment:
      POSTGRES_DB: "test_postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./postgres:/data/postgres
    #      - .:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  springboot:
    image: registry.hub.docker.com/jirafus400/spring_postgres
    container_name: springboot_container
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres_container:5432/test_postgres
    depends_on:
      - postgres
      - eureka-server

    ## Eureka Server
  eureka-server:
    image: registry.hub.docker.com/jirafus400/eureka-server
    container_name: eureka-server
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=docker


